spring.application.name=demo
spring.main.log-startup-info=false

# Bungkam semua log INFO, hanya tampilkan WARN dan ERROR
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.apache.tomcat=WARN
logging.level.org.apache.catalina=WARN
